apiVersion: v1
kind: ConfigMap
metadata:
  name: event-booking-config
  namespace: online-event-booking-abdullah-aslam

data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5433"
  MONGO_HOST: mongodb
  MONGO_PORT: "27017"
  USER_SERVICE_URL: "http://user-service:8000"
  EVENT_SERVICE_URL: "http://event-service:8001"
  BOOKING_SERVICE_URL: "http://booking-service:8002"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8003"
  FRONTEND_SERVICE_URL: "http://frontend-service:8080"
